package mapper;

import entity.Administrator;
import entity.AdministratorExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;

@Component
public interface AdministratorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    int countByExample(AdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    int deleteByExample(AdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Integer administratorid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    int insert(Administrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    int insertSelective(Administrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    List<Administrator> selectByExample(AdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    Administrator selectByPrimaryKey(Integer administratorid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    int updateByExampleSelective(@Param("record") Administrator record, @Param("example") AdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    int updateByExample(@Param("record") Administrator record, @Param("example") AdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(Administrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    int updateByPrimaryKey(Administrator record);
}