package mapper;

import entity.History;
import entity.HistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
public interface HistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history
     *
     * @mbggenerated Sat Dec 10 21:18:30 GMT+08:00 2022
     */
    int countByExample(HistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history
     *
     * @mbggenerated Sat Dec 10 21:18:30 GMT+08:00 2022
     */
    int deleteByExample(HistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history
     *
     * @mbggenerated Sat Dec 10 21:18:30 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Integer historyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history
     *
     * @mbggenerated Sat Dec 10 21:18:30 GMT+08:00 2022
     */
    int insert(History record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history
     *
     * @mbggenerated Sat Dec 10 21:18:30 GMT+08:00 2022
     */
    int insertSelective(History record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history
     *
     * @mbggenerated Sat Dec 10 21:18:30 GMT+08:00 2022
     */
    List<History> selectByExample(HistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history
     *
     * @mbggenerated Sat Dec 10 21:18:30 GMT+08:00 2022
     */
    History selectByPrimaryKey(Integer historyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history
     *
     * @mbggenerated Sat Dec 10 21:18:30 GMT+08:00 2022
     */
    int updateByExampleSelective(@Param("record") History record, @Param("example") HistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history
     *
     * @mbggenerated Sat Dec 10 21:18:30 GMT+08:00 2022
     */
    int updateByExample(@Param("record") History record, @Param("example") HistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history
     *
     * @mbggenerated Sat Dec 10 21:18:30 GMT+08:00 2022
     */
    int updateByPrimaryKeySelective(History record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table history
     *
     * @mbggenerated Sat Dec 10 21:18:30 GMT+08:00 2022
     */
    int updateByPrimaryKey(History record);
}