package entity;

import org.springframework.stereotype.Repository;

@Repository
public class Administrator {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.administratorid
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    private Integer administratorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.administratorname
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    private String administratorname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.password
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator.img
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    private String img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.administratorid
     *
     * @return the value of administrator.administratorid
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    public Integer getAdministratorid() {
        return administratorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.administratorid
     *
     * @param administratorid the value for administrator.administratorid
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    public void setAdministratorid(Integer administratorid) {
        this.administratorid = administratorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.administratorname
     *
     * @return the value of administrator.administratorname
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    public String getAdministratorname() {
        return administratorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.administratorname
     *
     * @param administratorname the value for administrator.administratorname
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    public void setAdministratorname(String administratorname) {
        this.administratorname = administratorname == null ? null : administratorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.password
     *
     * @return the value of administrator.password
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.password
     *
     * @param password the value for administrator.password
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator.img
     *
     * @return the value of administrator.img
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator.img
     *
     * @param img the value for administrator.img
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }
}