package entity;

import org.springframework.stereotype.Repository;

@Repository
public class History {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.historyid
     *
     * @mbggenerated Sat Dec 10 21:18:30 GMT+08:00 2022
     */
    private Integer historyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.userid
     *
     * @mbggenerated Sat Dec 10 21:18:30 GMT+08:00 2022
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.movieid
     *
     * @mbggenerated Sat Dec 10 21:18:30 GMT+08:00 2022
     */
    private Integer movieid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column history.history_time
     *
     * @mbggenerated Sat Dec 10 21:18:30 GMT+08:00 2022
     */
    private Float historyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.historyid
     *
     * @return the value of history.historyid
     *
     * @mbggenerated Sat Dec 10 21:18:30 GMT+08:00 2022
     */
    public Integer getHistoryid() {
        return historyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.historyid
     *
     * @param historyid the value for history.historyid
     *
     * @mbggenerated Sat Dec 10 21:18:30 GMT+08:00 2022
     */
    public void setHistoryid(Integer historyid) {
        this.historyid = historyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.userid
     *
     * @return the value of history.userid
     *
     * @mbggenerated Sat Dec 10 21:18:30 GMT+08:00 2022
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.userid
     *
     * @param userid the value for history.userid
     *
     * @mbggenerated Sat Dec 10 21:18:30 GMT+08:00 2022
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.movieid
     *
     * @return the value of history.movieid
     *
     * @mbggenerated Sat Dec 10 21:18:30 GMT+08:00 2022
     */
    public Integer getMovieid() {
        return movieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.movieid
     *
     * @param movieid the value for history.movieid
     *
     * @mbggenerated Sat Dec 10 21:18:30 GMT+08:00 2022
     */
    public void setMovieid(Integer movieid) {
        this.movieid = movieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column history.history_time
     *
     * @return the value of history.history_time
     *
     * @mbggenerated Sat Dec 10 21:18:30 GMT+08:00 2022
     */
    public Float getHistoryTime() {
        return historyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column history.history_time
     *
     * @param historyTime the value for history.history_time
     *
     * @mbggenerated Sat Dec 10 21:18:30 GMT+08:00 2022
     */
    public void setHistoryTime(Float historyTime) {
        this.historyTime = historyTime;
    }
}