package entity;

import org.springframework.stereotype.Repository;

@Repository
public class Mark {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mark.userid
     *
     * @mbggenerated Wed Dec 14 13:24:47 GMT+08:00 2022
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mark.movieid
     *
     * @mbggenerated Wed Dec 14 13:24:47 GMT+08:00 2022
     */
    private Integer movieid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mark.score
     *
     * @mbggenerated Wed Dec 14 13:24:47 GMT+08:00 2022
     */
    private Float score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mark.userid
     *
     * @return the value of mark.userid
     *
     * @mbggenerated Wed Dec 14 13:24:47 GMT+08:00 2022
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mark.userid
     *
     * @param userid the value for mark.userid
     *
     * @mbggenerated Wed Dec 14 13:24:47 GMT+08:00 2022
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mark.movieid
     *
     * @return the value of mark.movieid
     *
     * @mbggenerated Wed Dec 14 13:24:47 GMT+08:00 2022
     */
    public Integer getMovieid() {
        return movieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mark.movieid
     *
     * @param movieid the value for mark.movieid
     *
     * @mbggenerated Wed Dec 14 13:24:47 GMT+08:00 2022
     */
    public void setMovieid(Integer movieid) {
        this.movieid = movieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mark.score
     *
     * @return the value of mark.score
     *
     * @mbggenerated Wed Dec 14 13:24:47 GMT+08:00 2022
     */
    public Float getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mark.score
     *
     * @param score the value for mark.score
     *
     * @mbggenerated Wed Dec 14 13:24:47 GMT+08:00 2022
     */
    public void setScore(Float score) {
        this.score = score;
    }
}