package entity;

import org.springframework.stereotype.Repository;

@Repository
public class Movie {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.movieid
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    private Integer movieid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.moviename
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    private String moviename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.moviearea
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    private String moviearea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.sort
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    private String sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.duration
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    private String duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.dateissued
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    private String dateissued;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.moviepath
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    private String moviepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.imagepath
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    private String imagepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.uploadpath
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    private String uploadpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.intro
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.grade
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    private Float grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie.number
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.movieid
     *
     * @return the value of movie.movieid
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    public Integer getMovieid() {
        return movieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.movieid
     *
     * @param movieid the value for movie.movieid
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    public void setMovieid(Integer movieid) {
        this.movieid = movieid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.moviename
     *
     * @return the value of movie.moviename
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    public String getMoviename() {
        return moviename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.moviename
     *
     * @param moviename the value for movie.moviename
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    public void setMoviename(String moviename) {
        this.moviename = moviename == null ? null : moviename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.moviearea
     *
     * @return the value of movie.moviearea
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    public String getMoviearea() {
        return moviearea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.moviearea
     *
     * @param moviearea the value for movie.moviearea
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    public void setMoviearea(String moviearea) {
        this.moviearea = moviearea == null ? null : moviearea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.sort
     *
     * @return the value of movie.sort
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.sort
     *
     * @param sort the value for movie.sort
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.duration
     *
     * @return the value of movie.duration
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    public String getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.duration
     *
     * @param duration the value for movie.duration
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    public void setDuration(String duration) {
        this.duration = duration == null ? null : duration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.dateissued
     *
     * @return the value of movie.dateissued
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    public String getDateissued() {
        return dateissued;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.dateissued
     *
     * @param dateissued the value for movie.dateissued
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    public void setDateissued(String dateissued) {
        this.dateissued = dateissued == null ? null : dateissued.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.moviepath
     *
     * @return the value of movie.moviepath
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    public String getMoviepath() {
        return moviepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.moviepath
     *
     * @param moviepath the value for movie.moviepath
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    public void setMoviepath(String moviepath) {
        this.moviepath = moviepath == null ? null : moviepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.imagepath
     *
     * @return the value of movie.imagepath
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    public String getImagepath() {
        return imagepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.imagepath
     *
     * @param imagepath the value for movie.imagepath
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    public void setImagepath(String imagepath) {
        this.imagepath = imagepath == null ? null : imagepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.uploadpath
     *
     * @return the value of movie.uploadpath
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    public String getUploadpath() {
        return uploadpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.uploadpath
     *
     * @param uploadpath the value for movie.uploadpath
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    public void setUploadpath(String uploadpath) {
        this.uploadpath = uploadpath == null ? null : uploadpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.intro
     *
     * @return the value of movie.intro
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.intro
     *
     * @param intro the value for movie.intro
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.grade
     *
     * @return the value of movie.grade
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    public Float getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.grade
     *
     * @param grade the value for movie.grade
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    public void setGrade(Float grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie.number
     *
     * @return the value of movie.number
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie.number
     *
     * @param number the value for movie.number
     *
     * @mbggenerated Wed Dec 14 13:27:57 GMT+08:00 2022
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}