package entity;

import org.springframework.stereotype.Repository;

@Repository
public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userid
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usename
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    private String usename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.img
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    private String img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userid
     *
     * @return the value of user.userid
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userid
     *
     * @param userid the value for user.userid
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usename
     *
     * @return the value of user.usename
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    public String getUsename() {
        return usename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usename
     *
     * @param usename the value for user.usename
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    public void setUsename(String usename) {
        this.usename = usename == null ? null : usename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.img
     *
     * @return the value of user.img
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.img
     *
     * @param img the value for user.img
     *
     * @mbggenerated Wed Dec 07 21:33:23 GMT+08:00 2022
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }
}